spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mizuka}
spring.datasource.username=Rediska4445
spring.datasource.password=idontknowthepassword

minio.url=${MINIO_URL:http://localhost:9000}
minio.endpoint=${MINIO_URL:http://localhost:9000}
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}
minio.accessKey=rootadmin
minio.secretKey=rootpassword
minio.buckets.covers=tracks-covers
minio.buckets.tracks=tracks