spring.application.name=mizuka

spring.profiles.active=prod

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.web.resources.cache.period=0

spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/resources/templates
spring.devtools.restart.exclude=static/**,public/**

spring.devtools.livereload.port=35729
