# release application settings for Mizuki-web
# created by Rediska4445 of 8.23.2026

# 1. Database section

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mizuka}
spring.datasource.username=Rediska4445
spring.datasource.password=idontknowthepassword

# 1.1 Database schema section

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=validate

# That shit is not working
#spring.jpa.properties.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.hbm2ddl.auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# 2. Storage section

minio.url=${MINIO_URL:http://localhost:9000}
minio.endpoint=${MINIO_URL:http://localhost:9000}
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}
minio.accessKey=rootadmin
minio.secretKey=rootpassword
minio.buckets.covers=tracks-covers
minio.buckets.tracks=tracks

# 3. Cache section

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-config.tracks.time-to-live=24h
spring.cache.redis.cache-config.track_sizes.time-to-live=24h

# 4. Brokers section

auto.create.topics.enable=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.consumer.group-id=mizuki-listeners-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.properties.fetch.max.wait.ms=5000
spring.kafka.consumer.properties.fetch.min.bytes=1
spring.kafka.listener.type=batch
offsets.topic.replication.factor=1

# 5. Files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB