-- 1 commit to V1 version

ALTER TABLE tracks DROP COLUMN IF EXISTS description;
ALTER TABLE tracks ADD COLUMN description TEXT;

ALTER TABLE tracks ADD COLUMN IF NOT EXISTS likes_count BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS plays_count BIGINT DEFAULT 0 NOT NULL;
